### ISSUE TITLE
"-S" is not recognized as an internal or external command

### ISSUE THREAD

**Issue by palaklive** [facebookincubator/memlab#24]
I have tried to run the default [demo app](https://github.com/facebookincubator/memlab#find-memory-leaks) as mentioned in the readme doc.

![image](https://user-images.githubusercontent.com/26590202/190557467-b8b407d2-f1c0-4bb4-9e25-a6951e63d906.png)

**Comment by JacksonGL** [comment]
@palaklive memlab doesn't provide a `npm start` command (it's not mentioned in the readme doc). Please follow the steps on the readme file and manually run the following command
```
memlab run --scenario the-scenario-file.js
```

**Comment by palaklive** [comment]
Hello @JacksonGL 

I have set up the project and add memlab as a developer dependency. So, basically `npm start` executes the `memlab run --scenario file`

**Comment by palaklive** [comment]
even the [following doc](https://facebookincubator.github.io/memlab/docs/guides/guides-detached-dom#1-clone-repo) gives the same error.

**Comment by JacksonGL** [comment]
@palaklive The ad hoc fix would be going to the `C:\Users\YourUserName\AppData\Roaming\npm\` folder, open the `memlab` file and remove `-S`.
(assuming you are using Windows and the main drive is C)

MemLab install commands checks if you are running on Windows and should auto remove the `-S` flag (only used on Mac OS and Linux).

I was able to reproduce the error you encountered from my Windows machines (either by installing the npm package or build it directly from Git repo). Can you provide more details on how you installed the memlab package?

**Comment by JacksonGL** [comment]
@palaklive I think I may know what happened. I have updated the npm package, please remove the `./node_modules` folder and `package-lock.json` file under your project rerun `npm install --dev memlab@latest` and see if it works.

Thanks for reporting this issue!

**Comment by palaklive** [comment]
Your guidance @JacksonGL is much appreciated, after tacking the pull from the [repo](https://github.com/facebookincubator/memlab) issue has been resolved
