### ISSUE TITLE
Not Headless and more examples

### ISSUE THREAD

**Issue by QAInsights** [facebookincubator/memlab#36]
As a performance, I do not have experience w/ Puppeteer. But I would like to heavily use to troubleshoot the client-side performance using Memlab. 

1. How do we run with non-headless mode? If I try with `headless: false` (from Puppeteer doc), it is not working.
2. It would be great, if we need more examples on the automation front.

Thanks.

**Comment by JacksonGL** [comment]
@QAInsights For MemLab CLI, use `--headful` to run memlab in headful mode, for example:
```
memlab run --scenario <scenario file> --headful
```

Please check out the documentation for more examples:
https://facebookincubator.github.io/memlab/docs/intro

**Comment by QAInsights** [comment]
Thanks @JacksonGL Yes, I already went throught the examples. I am looking for automation scripts e.g. login, extracting token/sessions etc.

**Comment by JacksonGL** [comment]
@QAInsights The automation part is done by invoking methods in `page` object from Puppeteer, there are plenty of examples online for automation with Puppeteer.

Puppeteer documentation: https://pptr.dev/
