### ISSUE TITLE
Can memlab support the disable-web-security option ?

### ISSUE THREAD

**Issue by ftniu** [facebookincubator/memlab#38]
Our app runs on a customized browser. And our servers do not allow cross-domain requests.
So we got cors error while using memlab.
Can memlab support the disable-web-security option ?

**Comment by JacksonGL** [comment]
Yes, we can add a `--disable-web-security` option in MemLab command line. 
You can also add the flag to your local build ([code pointer](https://github.com/facebookincubator/memlab/blob/main/packages/core/src/lib/Config.ts#L276)).
